PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS playlist (
    playlistId INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL DEFAULT '',
    updated INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS image (
    imageId INTEGER PRIMARY KEY AUTOINCREMENT,
    sm TEXT NOT NULL DEFAULT '',
    lg TEXT NOT NULL DEFAULT '',
    position INTEGER NOT NULL DEFAULT 9999,
    playlistId INTEGER DEFAULT NULL REFERENCES playlist (playlistId) ON DELETE CASCADE ON UPDATE CASCADE        
);

CREATE TABLE IF NOT EXISTS device (
    deviceId INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL DEFAULT '',
    ip TEXT NOT NULL DEFAULT '',
    updated INTEGER NOT NULL DEFAULT 0,
    playlistId INTEGER DEFAULT NULL REFERENCES playlist (playlistId) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS user (
    userId INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL DEFAULT '',
    passhash TEXT NOT NULL DEFAULT '',
    permission TEXT NOT NULL DEFAULT 'user'
);